# -- metadata --------------------------------------------------------------
schema_version = "1.0"

name   = "Cloze with Source"
tags   = ["statistics"]
sortf  = 0   # use field index 0 ("Text") for sorting

# this controls ordering in Anki’s editor
field_order = ["Text", "Extra", "Source"]

# defaults for all fields
[defaults]
font = "Arial"
size = 20
rtl  = false

# per-field overrides
[[fields]]
name   = "Text"
ord    = 0
sticky = true
media  = []

[[fields]]
name   = "Extra"
ord    = 1
sticky = false
media  = []

[[fields]]
name   = "Source"
ord    = 2
sticky = true
media  = []

# controls which template is shown first
template_order = ["Cloze"]

# array-of-tables: one block per template
[[templates]]
name            = "Cloze"
ord             = 0
required_fields = ["Text"]


