[deck]
description = ""
name = ""
license = ""

[[schedules]]
name       = "Default"
max_taken  = 90
replayq    = true
timer      = 0

[schedules.lapse]
delays      = [10]
leech_action = 1
leech_fails  = 6
min_int      = 1
mult         = 0.3

[schedules.new]
bury           = true
delays         = [15, 2160, 10080, 43200]
initial_factor = 2500
ints           = [45, 50]
order          = 1
per_day        = 40
separate       = true

[schedules.rev]
bury        = true
ease4       = 1.3
fuzz        = 0.05
hard_factor = 1.2
ivl_fct     = 1.2
max_ivl     = 36500
min_space   = 1
per_day     = 350

