schema_version = "1.0.0"

name   = "Cloze with Source"
tags   = ["statistics"]
required = "Question"
sort_field  = "Text"   # use field index 0 ("Text") for sorting

# per-field overrides (if you don't need to define sticky or associated media, this is as simple as it gets)
fields = [
  { name = "Question" },
  { name = "Answer" }
]

# The order in which templates are defined is the order in which they are displayed
templates = [
  { name = "Cloze" }
]

